name: Android CI - Build & Test

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Prog7313POE

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: List files (debug)
        run: ls -la

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Run tests
        run: ./gradlew test

      - name: Build the project
        run: ./gradlew build
